### ISSUE TITLE
Missing cell locations parquet, source 5, plate ATSJUM206

### ISSUE THREAD

**Issue by Arkkienkeli** [jump-cellpainting/datasets#102]
The cell locations file that is supposed to exist by url 
```
s3://cellpainting-gallery/cpg0016-jump/source_5/workspace/load_data_csv/JUMPCPE-20210730-Run14_20210731_000211/ATSJUM206/load_data_with_illum_and_cell_location.parquet
```
does not exist. 

![image](https://github.com/jump-cellpainting/datasets/assets/3052376/9435a136-e74c-4479-a0b5-e464288309d4)

**Comment by shntnu** [comment]
Turns out we had reported this issue internally but it was unresolved (ref: https://github.com/jump-cellpainting/aws/issues/75#issuecomment-1531518014). Thankfully the `analysis` files are available so we can regenerate it.

Here are the steps to follow

https://cytomining.github.io/profiling-handbook/05-create-profiles.html#create-database-backend

```bash
mkdir -p ~/ebs_tmp/${PROJECT_NAME}/workspace/software

cd ~/ebs_tmp/${PROJECT_NAME}/workspace/software

if [ -d pycytominer ]; then rm -rf pycytominer; fi

git clone https://github.com/cytomining/pycytominer.git

cd pycytominer

python3 -m pip install -e .[collate]
```

and then

```bash
BATCH_ID="JUMPCPE-20210730-Run14_20210731_000211"
PLATE="ATSJUM206"
python3 pycytominer/cyto_utils/collate_cmd.py ${BATCH_ID}  pycytominer/cyto_utils/database_config/ingest_config.ini ${PLATE} \
--tmp-dir ~/ebs_tmp \
--aws-remote=s3://cellpainting-gallery/cpg0016-jump/source_5/workspace
```

I'll chat with @ashah03 about this and he will loop back

**Comment by shntnu** [comment]
@ashah03 -- `ATSJUM206.sqlite` is ready

```
aws s3 ls s3://cellpainting-gallery/cpg0016-jump/source_5/workspace/backend/JUMPCPE-20210730-Run14_20210731_000211/ATSJUM206/
2022-10-21 00:42:32          0 
2024-03-14 05:17:09   54929099 ATSJUM206.csv
2024-03-14 04:22:44 44989165568 ATSJUM206.sqlite
```

**Comment by shntnu** [comment]
Thanks a lot @ashah03!

@Arkkienkeli – all set here

```
aws s3 cp s3://staging-cellpainting-gallery/cpg0016-jump/source_5/workspace/load_data_csv/JUMPCPE-20210730-Run14_20210731_000211/ATSJUM206/load_data_with_illum_and_cell_location
.parquet s3://cellpainting-gallery/cpg0016-jump/source_5/workspace/load_data_csv/JUMPCPE-20210730-Run14_20210731_000211/ATSJUM206/load_data_with_illum_and_cell_location.parquet

aws s3 ls s3://staging-cellpainting-gallery/cpg0016-jump/source_5/workspace/load_data_csv/JUMPCPE-20210730-Run14_20210731_000211/ATSJUM206/load_data_with_illum_and_cell_location
.parquet
2024-03-14 19:22:48   14826148 load_data_with_illum_and_cell_location.parquet
```

**Comment by ashah03** [comment]
@shntnu can we move this file to s3://cellpainting-gallery (not staging) since everything else is there?

**Comment by shntnu** [comment]
From @ashah03 

We are unable to create the cell locations files for some plates because we run out of memory. We don't know whether this is to do with the SQLite file or the load_data CSV file

SQLite I generated for which cell locations does NOT generated

s3://staging-cellpainting-gallery/cpg0016-jump/source_3/workspace/backend/CP_25_all_Phenix1/C13443aW/C13443aW.sqlite

Corresponding load data Parquet file:

s3://cellpainting-gallery/cpg0016-jump/source_3/workspace/load_data_csv/CP_25_all_Phenix1/C13443aW/load_data_with_illum.parquet

SQLite for which cell locations does get generated

s3://cellpainting-gallery/cpg0016-jump/source_3/workspace/backend/CP60/BR5872b3/BR5872b3.sqlite

Corresponding load data Parquet file:

s3://cellpainting-gallery/cpg0016-jump/source_3/workspace/load_data_csv/CP60/BR5872b3/load_data_with_illum.parquet

**Comment by shntnu** [comment]
@ashah03 to wrap this up, can you please do the following

- Briefly pen down what you tried
- Isolate whether it is the load data or the SQLite that is causing the issue using the strategy we discussed

We can return to this later so that you can keep moving for now

@Arkkienkeli - we seem to have hit a wall but there has to be a fix. I'll ask Cimini lab if they have any ideas on what could be wrong with the SQLite (if indeed it is the SQLite)

**Comment by ashah03** [comment]
@shntnu moving to https://github.com/jump-cellpainting/datasets-private/issues/71 since this issue (source 5) is resolved
