### ISSUE TITLE
Exact commit hashes for Cellprofiler pipelines used in JUMP production

### ISSUE THREAD

**Issue by hanslovsky** [jump-cellpainting/datasets#82]
Is there documentation for the exact version and commit hash of the cellprofiler pipelines that were used by each source for analysis? https://github.com/broadinstitute/imaging-platform-pipelines/tree/master/JUMP_production#production-pipelines is linked in the paper but there are two pipeline (`JUMP_analysis_v2.cppipe` and `JUMP_analysis_v3.cppipe`). Did all sources use the same pipeline (v3?) at the same commit hash?

Thank you

**Comment by niranjchandrasekaran** [comment]
I believe everyone used v3. Tagging @bethac07, who can confirm.

**Comment by bethac07** [comment]
Everyone used the measurements in v3, but classical segmentation is typically not robust enough to not need tweaking across multiple sites - sometimes not even across multiple batches. So segmentation steps were not held constant across sites - for sources that sent Experiment.csv files, those will record exact settings for each plate, otherwise you'd need to get pipelines from each source and confirm which batch(es) each was used for.

**Comment by hanslovsky** [comment]
Great, thank you @bethac07 and @niranjchandrasekaran!
