### ISSUE TITLE
How to obtain ORF features

### ISSUE THREAD

**Issue by zhanggyuuuuu** [jump-cellpainting/datasets#88]
May I ask how the data containing 1477 features is obtained for the Umap map drawn by analyzing ORF data in the article?  What is the relationship between the data containing 1477 features and the data containing 7648 features or 4762 features?  Are these 1,477 features derived from 7,648 features processed?
Thanks for answers.

**Comment by niranjchandrasekaran** [comment]
> Are these 1,477 features derived from 7,648 features processed?

Hi @zhanggyuuuuu, yes, we performed feature selection to remove both redundant features and invariant features. This resulted in 1477 features for the ORF dataset that was in the manuscript. I should note that we have since changed our post-processing steps and the updated ORF dataset (not yet released) will have a different number of features.

**Comment by zhanggyuuuuu** [comment]
Hi～May I inquire whether you have updated the dataset of ORF original experimental images or if the update pertains to further processing derived from the initial 7648 features? I greatly appreciate your clarification on this matter.

**Comment by niranjchandrasekaran** [comment]
Hi @zhanggyuuuuu, the images and the features extracted from CellProfiler (7648 features) haven't changed. Only the downstream processing steps and the resulting features are now different.
